github_url = "https://github.com/nogara/pr-labels-action/"

[version]
current = "1.1.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "package.json"
search = '"version": "{current_version}"'

[[file]]
src = "README.md"
search = 'nogara/pr-labels-action@v{current_version}'

[[before_commit]]
name = "Run pre-commit"
cmd = "pre-commit run -a"
